---

- name: 'Creating base directories for {{ ghost__blog_name }}'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: '755'
    state: directory
  loop:
    - '{{ ghost__base_dir }}'
    - '{{ ghost__base_dir }}/content'
    - '{{ ghost__base_dir }}/db'

- name: 'Creating config file for {{ ghost__blog_name }}'
  ansible.builtin.template:
    src: "templates/podman_env.j2"
    dest: "{{ ghost__base_dir }}/podman_env"
    owner: root
    group: root
    mode: '600'

- name: 'Creating network for {{ ghost__blog_name }}'
  containers.podman.podman_network:
    name: '{{ ghost__network_name }}'
    subnet: '{{ ghost__network_cidr }}'
    gateway: '{{ ghost__network_gateway }}'
    state: present

- name: "Setup ghost's podman container for {{ ghost__blog_name }}"
  containers.podman.podman_container:
    name: 'ghost_{{ ghost__host | regex_replace("[\.\/]", "_") }}'
    image: 'docker.io/ghost:{{ ghost__version }}-alpine'
    env_file: "{{ ghost__base_dir }}/podman_env"
    network: '{{ ghost__network_name }}'
    mount:
      - "type=bind,source={{ ghost__base_dir }}/content,destination=/var/lib/ghost/content"
    ports:
      - "{{ ghost__listen_host }}:{{ ghost__listen_port }}:2368/tcp"
    restart_policy: 'unless-stopped'
    state: started
